### ISSUE TITLE
Add hapi

### ISSUE THREAD

**Issue by cjihrig** [rvagg/iojs-smoke-tests#1]
hapi might be a good option to include. It is pretty heavily used, and maintains 100% test coverage.

**Comment by hueniverse** [comment]
I would add that until and unless hapi is an official part of the release smoke tests (it was part of the Joyent release process for node.js 0.10 and 0.12), I will not be officially supporting io.js or node.js 4.x for at least 6 months to a year after their release. The companies using hapi are mostly major enterprises with a very low risk tolerance.

If there are ways for the hapi community to help in this process, please let us know and we will gladly contribute. Moving hapi to the latest version of io/node would be a huge win for everyone.

**Comment by rvagg** [comment]
Moved to https://github.com/nodejs/citgm/issues/8, this tool is being deprecated in favour of citgm (probably) for more comprehensive cross-platform testing.
